---

- name: Deploying docker image 

  hosts: all

  become: true

  tasks:
        - name: Log into private registry and force re-authorization
          docker_login:
            registry_url: 13.68.151.232:8085
            username: admin
            password: admin@123
            reauthorize: true
        - name: excuting the container
          docker_container:
            name: chatapp
            image: 13.68.151.232:8085/chatapp
            state: started
            pull: 'true'
            ports:
            - "8082:8080"
        - name: port 8080
          tags: test
          uri:
            url: http://localhost:8080
          register: result
          until: "result.status == 200"
          retries: 5
          delay: 10
